package common;

/**
 * Created by furqan on 04/03/2019.
 */
public enum Metric {
    NUM_OF_IMPRESSIONS, NUM_OF_CLICKS, NUM_OF_UNIQUE_CLICKS, NUM_OF_BOUNCES, NUM_OF_CONVERSIONS, TOTAL_COST, CTR, CPC, CPM, CPA, BOUNCE_RATE
}
